apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubevuln
rules:
- apiGroups:
  - spdx.softwarecomposition.kubescape.io
  resources:
  - vulnerabilitymanifests
  - vulnerabilitymanifestsummaries
  - openvulnerabilityexchangecontainers
  - sbomsyfts
  - sbomsyftfiltereds
  verbs:
  - create
  - get
  - update
  - watch
  - list
  - patch
- apiGroups:
  - spdx.softwarecomposition.kubescape.io
  resources:
  - applicationprofiles
  verbs:
  - get
  - watch
  - list
# NEW: Add permissions for scanreports.kubevuln.io
- apiGroups:
  - kubevuln.io
  resources:
  - scanreports
  verbs:
  - create
  - get
  - update
  - watch
  - list
  - patch 