apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: scanreports.kubevuln.io
spec:
  group: kubevuln.io
  names:
    kind: ScanReport
    listKind: ScanReportList
    plural: scanreports
    singular: scanreport
  scope: Namespaced
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
                description: "The image that was scanned"
              namespace:
                type: string
                description: "The namespace where the scan was performed"
              timestamp:
                type: string
                description: "The time when the scan was performed"
              clusterName:
                type: string
                description: "The cluster where the scan was performed"
              jobID:
                type: string
                description: "Unique identifier for the scan job"
              diveReport:
                type: string
                description: "Complete dive analysis report as JSON string"
              trufflehogReport:
                type: string
                description: "Complete trufflehog secrets scan report as JSON string"
              reportPath:
                type: string
                description: "Path to the local report files"
              reports:
                type: object
                description: "Additional reports from other tools"
                additionalProperties: true
            required:
            - image
            - namespace
            - timestamp
          status:
            type: object
            properties:
              status:
                type: string
                description: "Current status of the scan report"
              lastUpdated:
                type: string
                description: "Last time the status was updated"
    additionalPrinterColumns:
    - name: Image
      type: string
      jsonPath: .spec.image
    - name: Namespace
      type: string
      jsonPath: .spec.namespace
    - name: Timestamp
      type: date
      jsonPath: .spec.timestamp
    - name: Status
      type: string
      jsonPath: .status.status
    - name: Age
      type: date
      jsonPath: .metadata.creationTimestamp 